### ISSUE TITLE
Add a nested comment explaining why this method is empty, throw an UnsupportedOperationException or complete the implementation.

### ISSUE THREAD

**Issue by Natzgun** [Natzgun/ProceedHub#7]
src/test/java/com/mistysoft/proceedhub/ProceedHubApplicationTests.java

**Comment by GiomarMC** [comment]
Se han agregado comentarios explicativos en el método contextLoads, se agregó la opción de lanzar una excepción UnsupportedOperationException  para validar la carga del contexto de la aplicación.
